{% set name = "vecstack" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vecstack-{{ version }}.tar.gz
  sha256: 14cd0d9d0f00388c66e80f6af95b8964d414b7343b5544ce37ab35d2761fcd26

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - scikit-learn >=0.18
    - scipy

test:
  imports:
    - vecstack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vecxoz/vecstack
  summary: Python package for stacking (machine learning technique)
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - izahn
